### ISSUE TITLE
標籤資料庫學名檔發現一些錯誤需修改

### ISSUE THREAD

**Issue by ghost** [TaiBIF/hast#1]
錯誤資料 竹柏屬 學名連結不存在

**Comment by moogoo78** [comment]
直接 insert失敗, 要再看看 SCHEMA 設定
 INSERT INTO dbo.vwGenus (familyID, familyApgIVID, genusID, genusE, genusC, genusExpr, infromal, familyE, familyC, classID, classC, classE) VALUES (206, 206, 193, 'Nageia', '竹柏屬', 'Nageia 竹柏屬', null, 'PODOCARPACEAE', '羅漢松科', 2, '裸子植物', 'GYMNOSPERMAE');

**Comment by moogoo78** [comment]
跟 #5 重複
