### ISSUE TITLE
2001、2003 彭老師美國採集_地點勘誤 (夏威夷州)

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#11]
@HASTboya 

[2001及2003_地點問題_夏威夷州.xlsx](https://github.com/TaiBIF/hast/files/3230606/2001.2003_._.xlsx)

此兩趟採集之HAST標本連結 : 
2001年- [http://www.hast.biodiv.tw/specimens/specimenListC.aspx?collectorID=90&collectionDate=2001-1-1&collectionDateEnd=2001-12-31&countryNo=6&altCompare=0](url)

2003年 - [http://www.hast.biodiv.tw/specimens/specimenListC.aspx?collectorID=90&collectionDate=2003-1-1&collectionDateEnd=2003-8-30&countryNo=6&altCompare=0](url)

**Comment by HASTboya** [comment]
@tsaiyuch 
查了標本和資料庫，標本標籤的州是Florida，但資料庫不知為何整批變Hawaii，如果不是資料跳掉那就是之前的工讀生某筆打錯後複製繼續key. 
我這找不到原始採集記錄，採集本No.11是手寫還是標籤列印版? 可能需要對照改資料庫

**Comment by HASTboya** [comment]
已修正
