### ISSUE TITLE
照片圖說_數博

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#12]
@KuoFangChung   請老師協助提供照片說明，謝謝老師。
[drive.google](https://drive.google.com/drive/folders/188D0AT9w2j5KYIDnboZwFUcLjQgCys5k?usp=sharing)

1. 照片事件 (簡述即可，例如 "彭老師與Peter H. Raven前往溪頭國家森林遊樂區")

2. 拍攝日期，可僅提供年份 (若無從得知則留白) 

3. 拍攝者姓名 (或是照片提供者姓名)

**Comment by KuoFangChung** [comment]
彭老師參與中國植物誌英文版編輯會議 (彭鏡毅提供)
2008年

**Comment by KuoFangChung** [comment]
彭老師與 Dr. Raven 夫婦於台大溪頭實驗林

**Comment by KuoFangChung** [comment]
2015 亞洲秋海棠暨石灰岩植物保育研究國際研討會與會嘉賓至屏東高樹辜嚴倬雲植物保種中心(KBCC) 參訪後合影。
鍾國芳攝

**Comment by KuoFangChung** [comment]
彭老師於美國聖路易市華盛頓大學/密蘇里植物園求學期間 (1978-1982) 與同學合影。
David Lorence (前排右一) 提供。

**Comment by KuoFangChung** [comment]
彭老師於美國聖路易市華盛頓大學/密蘇里植物園求學期間 (1978-1982) 與同學合影。
David Lorence (右一) 提供。

**Comment by KuoFangChung** [comment]
2009年四月4日Dr. Peter Raven 應 "龍應台文化基金會"邀請至"國際名家論壇"演講後餐會，彭鏡毅老師 (中)、Dr. Peter Raven (右)、鍾國芳 (左) 合影。
鍾國芳提供

**Comment by KuoFangChung** [comment]
彭鏡毅老師與 Dr. Peter Raven 夫婦於墾丁鵝鑾鼻燈塔合影。
2011年11月
鍾國芳攝 (這張 Dr. Raven 眼睛是閉的)

**Comment by KuoFangChung** [comment]
Peter Raven 夫婦、彭老師、林試所研究員伍淑惠攝於墾丁公園。
2011年11月
鍾國芳攝

**Comment by KuoFangChung** [comment]
彭老師於美國聖路易市華盛頓大學/密蘇里植物園求學期間 (1978-1982) 與同學合影。
Warren Wagner 提供。
(我還在詢問更多細節)

**Comment by KuoFangChung** [comment]
彭鏡毅老師碩士班指導教授許建昌博士。
許建昌教授於2010年獲頒臺灣植物分類學會終生貢獻獎會場留影。
楊智凱攝

**Comment by KuoFangChung** [comment]
彭老師與在美留學期間指導教授 Dr. Peter Raven (右二) 及友人 Dr. Peter Hoch (左二)、Dr. David Boufford (左一) 合影。
攝於 "53rd Annual Systematics Symposium Missouri Botanical Garden" "The Impact of Peter Raven on Evolutionary and Biodiversity Issues in the 20th and 21st Centuries"
彭鏡毅提供
Dr. Peter Raven 退休研討會。

**Comment by tsaiyuch** [comment]
@KuoFangChung 
[雲端上的照片](https://drive.google.com/drive/folders/1a7mqzAfWpRDoK2Wwrf1UczoU2I43DWdc)，需請老師提供**照片事件說明**

謝謝老師!

**Comment by tsaiyuch** [comment]
@KuoFangChung 
請見上方資訊，謝謝老師!
