### ISSUE TITLE
HAST標本

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#13]
@moogoo78 思賢好，

[HAST_菊科_20190603.xlsx](https://github.com/TaiBIF/hast/files/3251009/HAST_._20190603.xlsx)

請協助打包文件中(內含兩個表格)的資料，包含 : 

**1. 標本資料庫 :**  標本照片、標本metadata 

**2. 影像資料庫 :**  影像照片、影像metadata 
本批影像都在此網址 [DICOTYLEDON 雙子葉植物 > ASTERACEAE 菊科](http://www.hast.biodiv.tw/Photo/ImageHierarchicalC.aspx?&familyID=539)

若時間能配合，請於下週一(6/10)之前給我，謝謝!!

**Comment by tsaiyuch** [comment]
@moogoo78  本ISSUE 內容稍早已更新，若有問題再麻煩通知，謝謝協助!!

**Comment by tsaiyuch** [comment]
@moogoo78  原先討論6/13完成list，請延後至6/14，我確認後會寄信通知您，謝謝!!

**Comment by moogoo78** [comment]
目前系統加了一個可以用多筆館號查詢的欄位, @tsaiyuch 給我的 excel 原本有 101 筆, 我這邊查出來的只有 97 筆, 還在找原因中...
[hast-dump.xlsx](https://github.com/TaiBIF/hast/files/3280795/hast-dump.xlsx)

**Comment by tsaiyuch** [comment]
@moogoo78  list共兩份。所需內容如下 : 
[HAST標本_菊科_20190610.xlsx](https://github.com/TaiBIF/hast/files/3284056/HAST._._20190610.xlsx)
[HAST標本(非菊科)_20190612.xlsx](https://github.com/TaiBIF/hast/files/3284552/HAST._20190612.xlsx)

- 標本資料庫 : 僅需打包**照片**給我  (metadata我自己抓)
- 影像資料庫 : 需打包**metadata**及**照片**給我

麻煩了，若有不清楚之處，可電話詢問，謝謝!!

**Comment by tsaiyuch** [comment]
@moogoo78  
此外，HAST - query 系統似乎一定要填寫 "採集者" 欄位才能查詢，若"採集者"欄位沒填，便會出現 Internal Server Error。
是否可以改成，只要有填"學名" 或 "科、屬" 等欄位亦能查詢，如同HAST網站，沒有限制一定要填"採集者"

**Comment by moogoo78** [comment]
> @moogoo78
> 此外，HAST - query 系統似乎一定要填寫 "採集者" 欄位才能查詢，若"採集者"欄位沒填，便會出現 Internal Server Error。
> 是否可以改成，只要有填"學名" 或 "科、屬" 等欄位亦能查詢，如同HAST網站，沒有限制一定要填"採集者"

這是個 bug, 已經修改上傳了

**Comment by moogoo78** [comment]
@tsaiyuch 

標本照片檔 (缺: 的數字是館號)

- [菊科](http://140.109.29.30/static/asteraceae.zip)
  - 缺: 131631
- [非菊科](http://140.109.29.30/static/non-asteraceae.zip)
  - 缺: 97412, 143886, 111887, 101774, 101775, 101776, 101781, 101787, 97436, 101788, 101791, 12576, 94883, 94884, 114470, 114474, 12591, 84272, 12600, 107972, 93901, 143950, 112083, 130516, 143958, 143959, 130518, 94941, 91120, 96116

**Comment by tsaiyuch** [comment]
@HASTboya 
以下標本於HAST網站上缺乏影像(共31)，請協助確認是否尚未掃描，謝謝!!
[缺標本影像.xlsx](https://github.com/TaiBIF/hast/files/3289353/default.xlsx)

@moogoo78  已收到照片
此外，菊科與非菊科剛好顛倒了，應是非菊科缺131631 ； 
菊科缺97412, 143886, 111887, 101774, 101775, 101776, 101781, 101787, 97436, 101788, 101791, 12576, 94883, 94884, 114470, 114474, 12591, 84272, 12600, 107972, 93901, 143950, 112083, 130516, 143958, 143959, 130518, 94941, 91120, 96116
此部分已自行處理，僅此回報讓你知道，謝謝!

**Comment by moogoo78** [comment]
影像資料庫的部分:
-  [菊科](http://140.109.29.30/static/photo-aster.zip)
-  [非菊科](http://140.109.29.30/static/photo-non-aster.zip)

**Comment by tsaiyuch** [comment]
@moogoo78  上方影像資料庫無法下載，點入後出現"無法連上這個網站"
請協助確認，謝謝!

**Comment by moogoo78** [comment]
@tsaiyuch 應該可以了, 週末那台主機不知什麼原因當掉...

**Comment by tsaiyuch** [comment]
@moogoo78 已收到 謝謝!
@HASTboya 標本影像再麻煩您了，謝謝!

**Comment by tsaiyuch** [comment]
@moogoo78  請協助爬清單中的 **經緯度** 資料
缺乏經緯度的 留白即可! 謝謝

[經緯度.xlsx](https://github.com/TaiBIF/hast/files/3323875/default.xlsx)

**Comment by moogoo78** [comment]
@tsaiyuch hast-query 可以查喔, 可以一次填一堆館號 (用逗號分隔, 中間不要有空白)

例如:
![Screen Shot 2019-06-26 at 11 05 35](https://user-images.githubusercontent.com/428769/60148151-875ebc00-9802-11e9-9a79-c0a2b54c5acd.png)

出來的結果 (欄位X, Y 是經緯度)
![Screen Shot 2019-06-26 at 11 05 45](https://user-images.githubusercontent.com/428769/60148188-a3625d80-9802-11e9-9026-79aeec9c6b36.png)

如果不方便的話我再用程式幫妳撈

**Comment by tsaiyuch** [comment]
@moogoo78  因資料筆數較多，麻煩你用程式幫忙撈! 謝謝!!

以及感謝改版HAST - query的查詢介面~~

**Comment by moogoo78** [comment]
@tsaiyuch 來了
[hast-dump.xlsx](https://github.com/TaiBIF/hast/files/3328697/hast-dump.xlsx)

**Comment by HASTboya** [comment]
@tsaiyuch 缺的標本影像來了
[https://drive.google.com/drive/folders/1TYvHhnr1iPF4-em6LTSezxdRs1BGfDpG?usp=sharing](url)
館號12591,84272標本失蹤中。
館號130516,130518也沒找到，但同採集號有另一張標本，你應該有抓到：館號7485874854
