### ISSUE TITLE
彭氏柳葉菜 Epilobium pengii C.J. Chen, Hoch & P.H. Raven

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#16]
@HASTboya 
本物種之 [發表文獻](https://www.jstor.org/stable/pdf/25027806.pdf?refreqid=excelsior%3Afda18c2cd2cbf8e3257af7ff542db460)
記錄HAST有Isotype (如下圖)，但並未查詢到，請協助確認，謝謝!!

![彭氏柳葉菜](https://user-images.githubusercontent.com/50312520/60419918-0300a480-9c19-11e9-920e-84747f6a227c.png)

**Comment by HASTboya** [comment]
！！我的list中從古到今都沒這種！！櫃子裡也沒有！！！
