### ISSUE TITLE
瓜葉向日葵 Helianthus debilis Nuttall subsp. cucumerifolius (Torrey & A. Gray) Heiser

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#17]
@HASTboya 
[發表文獻](http://tai2.ntu.edu.tw/taiwania/pdf/tai.2008.53.316.pdf) 
記述HAST有標本 : C.H. Lin 299 

於網站上沒有查到，請協助確認! 謝謝

**Comment by HASTboya** [comment]
館號83381，應該是沒人訂正
http://www.hast.biodiv.tw/specimens/specimenListC.aspx?&specimenOrderNum=83381&altCompare=0

**Comment by tsaiyuch** [comment]
ok，請協助訂正標本後設資料，謝謝!!
