### ISSUE TITLE
山蟛蜞菊 Wollastonia montana (Blume) DC.

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#18]
@HASTboya 
文獻 : [台灣菊科的新紀錄植物－山蟛蜞菊](https://tesri.tesri.gov.tw/files/tesri_protect/tesri_journal_20141120141312/Wollastonia%20montana.pdf)
說明 [C. I Peng 6910 (HAST)](http://www.hast.biodiv.tw/specimens/SpecimenDetailC.aspx?specimenOrderNum=47344) 該份標本為**山蟛蜞菊Wollastonia montana (Blume) DC.**，而非雙花蟛蜞菊。

請協助訂正標本資訊，謝謝!!

**Comment by tsaiyuch** [comment]
以及請寄這份標本的影像給我!! 謝謝

**Comment by HASTboya** [comment]
已改
