### ISSUE TITLE
HAST菊科標本_彭鏡毅老師

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#19]
@moogoo78 
在HAST上設定搜尋條件 : 採集者為**彭鏡毅老師** + 科名為**菊科**  [連結](http://www.hast.biodiv.tw/specimens/specimenListC.aspx?&collectorID=90&familyID=539&altCompare=0)

因達搜尋筆數上限3000筆，故無法得知彭老師採集之菊科標本，共有多少份?
請問能從後台得知嗎，謝謝!

**Comment by tsaiyuch** [comment]
@moogoo78 
請協助爬hast資料及打包標本影像，搜尋條件 : **彭鏡毅老師**採集之**菊科**標本。如上方連結

以及麻煩將**欠缺標本影像**的資料，另外放在一份excel，不與有標本影像的資料混在同一份excel，謝謝!!

此檔案中的館號已有，不需要再給一次~ 感謝!!!
[HAST菊科標本_已有.xlsx](https://github.com/TaiBIF/hast/files/3409868/HAST._.xlsx)

**Comment by moogoo78** [comment]
@tsaiyuch 這幾天在趕匯入世斌的冷凍遺傳資料庫，下週再處理這件事可以嗎

**Comment by tsaiyuch** [comment]
@moogoo78  ok!!謝謝

**Comment by tsaiyuch** [comment]
@moogoo78 
再麻煩你了!! 若上方描述有不清楚處，再麻煩電話詢問，感謝!!

**Comment by tsaiyuch** [comment]
@moogoo78 請問這週方便處理嗎? 謝謝

**Comment by moogoo78** [comment]
彭老師的菊科標本的資料
(原本資料庫雖然上限是 3000 筆，但是其實很多是重複的，實際計算只有 2627 筆)

https://www.dropbox.com/sh/w6xpvh5frcwhs6p/AACNlsdkaDsArsx059cqt52ka?dl=0

- peng-asteraceae-all.xlsx: 全部, 沒有分有圖片還是沒有圖片
- peng-asteraceae-has-image.xlsx: 有照片的
- peng-asteraceae-no-image.xlsx: 沒照片的
- images-peng-asteraceae.zip 照片 (這邊理論上會比 HAST 網站完整, 是跟翠雅掃描結果同步的, 如果沒有的話應該就是還沒掃)

**Comment by tsaiyuch** [comment]
好的我近期整理，若有問題再回覆! 謝謝
