### ISSUE TITLE
BEGONIACEAE 秋海棠科_HAST 影像資料庫

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#21]
@moogoo78 

[連結](http://www.hast.biodiv.tw/Photo/ImageHierarchicalC.aspx?&familyID=453)

請協助打包影像圖檔以及後設資料，謝謝!!

此部分打包資料不急(預計明年策展使用)，**但能否於本週五前告知**，**總共有幾張圖?** 

感謝!!!

**Comment by moogoo78** [comment]
檔案在這邊, 共 431 張圖
https://www.dropbox.com/sh/mfbdyp0prhs4b5q/AADkGzmvbSKl3lUzW6ch4hmYa?dl=0

**Comment by tsaiyuch** [comment]
最近發現 http://140.109.29.30/query/hast  連不進去
請協助處理，謝謝!

moogoo <notifications@github.com> 於 2019年8月23日 週五 下午2:09寫道：

**Comment by moogoo78** [comment]
@tsaiyuch 現在應該可以了

**Comment by tsaiyuch** [comment]
可以了! 謝謝

moogoo <notifications@github.com> 於 2019年9月18日 週三 下午5:29寫道：
