### ISSUE TITLE
2001美國_水丁香屬標本

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#25]
@moogoo78 
請協助打包"標本影像"，共96張圖，謝謝!

2001年彭老師在美國所採集之水丁香屬植物 [HAST](http://www.hast.biodiv.tw/specimens/specimenListC.aspx?collectorID=90&collectionDate=2001-1-1&collectionDateEnd=2001-12-31&countryNo=6&altCompare=0)

**Comment by tsaiyuch** [comment]
11/12 經電話確認，思賢暫定於**12/2-6**間協助打包。感謝

**Comment by tsaiyuch** [comment]
12/2 思賢協助打包影像的時間更正為 12/9-13

**Comment by moogoo78** [comment]
@tsaiyuch 打包好了, 共 96 張
[us-ludwigia.zip](https://github.com/TaiBIF/hast/files/3938812/us-ludwigia.zip)

**Comment by tsaiyuch** [comment]
@moogoo78 
收到謝謝!
不過我這裡看是 *95 *個檔案，不曉得是少了哪一份，再麻煩您協助確認了! 謝謝

moogoo <notifications@github.com> 於 2019年12月9日 週一 下午5:22寫道：

**Comment by moogoo78** [comment]
@tsaiyuch 少這個, @HASTboya 說也找不到標本
http://www.hast.biodiv.tw/specimens/SpecimenDetailC.aspx?specimenOrderNum=99980

**Comment by tsaiyuch** [comment]
ok 感謝!
