### ISSUE TITLE
HAST影像&標本資料庫_待訂正

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#28]
@HASTboya 今日討論之內容，簡要紀錄如下，謝謝您!

**影像資料庫**
[纓絨花](http://www.hast.biodiv.tw/Photo/ImageHierarchicalC.aspx?&familyID=539&genusID=1616)之前五張照片，訂正為 : 粉黃纓絨花 (_Emilia praetermissa_ Milne-Redh.)
ID:0002699、0002701、0002702、0002704、0002710
![學名需修正](https://user-images.githubusercontent.com/50312520/77513307-b4ceb800-6eaf-11ea-86bb-51e82337ff59.jpg)

**標本資料庫**
請依據文獻，將台灣黃鵪菜，訂正為 : 山間黃鵪菜 (_Youngia japonica_ subsp. _monticola_ Koh Nakam. & C.I Peng)
[2013-Youngia.pdf](https://github.com/TaiBIF/hast/files/4379600/2013-Youngia.pdf)

**Comment by HASTboya** [comment]
除了Koh的號碼外，6份標本已訂正為山間黃鵪菜

**Comment by tsaiyuch** [comment]
今日討論 : 除上述6份標本 (HAST2448, 2455, 90150, 19978, 17092, 119372) 已訂正，文獻中尚有其他標本也需一併修正，待翠雅後續回覆，謝謝!

**Comment by HASTboya** [comment]
所以最後一頁的山間黃鵪菜參考標本全是paratype?

**Comment by HASTboya** [comment]
除了Koh的號碼外，文章中列出標本已訂正為山間黃鵪菜
http://www.hast.biodiv.tw/specimens/specimenListC.aspx?familyID=539&genusID=1683&speciesID=107395&altCompare=0

**Comment by tsaiyuch** [comment]
收到，謝謝!
