### ISSUE TITLE
HAST英文版 無法呈現標本影像

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#36]
@moogoo78 請思賢協助排解問題，謝謝。

舉例：
HAST94990 [英文版無影像](http://www.hast.biodiv.tw/specimens/SpecimenDetailE.aspx?specimenOrderNum=94990)；[中文版正常](http://www.hast.biodiv.tw/specimens/SpecimenDetailC.aspx?specimenOrderNum=94990)

HAST117600 [英文版無影像](http://www.hast.biodiv.tw/specimens/SpecimenDetailE.aspx?specimenOrderNum=117600)；[中文版正常](http://www.hast.biodiv.tw/specimens/SpecimenDetailC.aspx?specimenOrderNum=117600)

HAST138450 [英文版無影像](http://www.hast.biodiv.tw/specimens/SpecimenDetailE.aspx?specimenOrderNum=138450)；[中文版正常](http://www.hast.biodiv.tw/specimens/SpecimenDetailC.aspx?specimenOrderNum=138450)

**Comment by moogoo78** [comment]
@tsaiyuch  已修正, 請再確認看看

**Comment by tsaiyuch** [comment]
已確認OK，感謝排解問題。
