### ISSUE TITLE
HAST標本照片 - 運用於開放博物館

### ISSUE THREAD

**Issue by tsaiyuch** [TaiBIF/hast#8]
@moogoo78 請協助打包HAST標本照片 [http://www.hast.biodiv.tw/specimens/specimenListC.aspx?collectorID=90&familyID=462&genusID=1080&countryNo=1&altCompare=0](url)

共104筆資料，皆有照片，謝謝!!

**Comment by tsaiyuch** [comment]
@moogoo78 請問此批能否於 5/23(四) 前打包給我呢?  感謝!!!

**Comment by moogoo78** [comment]
@tsaiyuch 總共只有 95 張標本照片，因為有一些是館號重複的副本 (共 9 筆)。

下載網址
http://140.109.29.30/static/img-190520.zip

**Comment by tsaiyuch** [comment]
收到 謝謝!
