### ISSUE TITLE
玉山蟹甲草的正確學名

### ISSUE THREAD

**Issue by KuoFangChung** [TaiBIF/hast#9]
玉山蟹甲草的正確學名應該為 Parasenecio morrisonensis Y. Liu, C.I Peng & Q.E. Yang，植物誌用的 Parasenecio monantha (Diels) C.I Peng & S.W.Chung 為中國西南植物 P. roborowskii (Maxim.) Y.L. Chen 的 synonym。
https://onlinelibrary.wiley.com/doi/abs/10.1002/tax.562029

**Comment by HASTboya** [comment]
所以...其他P. monantha標本都要貼訂正條?

**Comment by KuoFangChung** [comment]
是的，有空請更正。

Kuo-Fang Chung, Ph.D.
Associate Research Fellow/Professor & 
Director of Research Museum
Biodiversity Research Center
Academia Sinica
128 Academia Road, Section 2, 
Nankang, Taipei 11529, 
TAIWAN 
+886-2-27872225 (Office)
+886-2-27872226 (Lab)

鍾國芳 副研究員 兼 生物多樣性研究博物館主任
中央研究院生物多樣性研究中心
11529 台北市南港區研究院路二段 128 號
02-27872225 (Office)
02-27872226 (Lab)

-----Original message-----

**Comment by HASTboya** [comment]
標示鍾老師訂正

**Comment by HASTboya** [comment]
完成
